USE [TMCDB]
GO

CREATE TABLE [ScrapTray](
	[ScrapID] INT IDENTITY (1,1) NOT NULL,
	[TimeStamp] DATETIME DEFAULT GETDATE(),

	);

	INSERT INTO ScrapTray
	(TimeStamp)
	VALUES
	(GETDATE()),
	(GETDATE());