//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XArrayTransitionPlot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default Profile")]
        public string ProfileName {
            get {
                return ((string)(this["ProfileName"]));
            }
            set {
                this["ProfileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SpeedwayR-10-5C-CF")]
        public string ReaderAddress {
            get {
                return ((string)(this["ReaderAddress"]));
            }
            set {
                this["ReaderAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MaxThroughput")]
        public global::Impinj.OctaneSdk.ReaderMode ReaderMode {
            get {
                return ((global::Impinj.OctaneSdk.ReaderMode)(this["ReaderMode"]));
            }
            set {
                this["ReaderMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public ushort InitialStraySearchTimeSec {
            get {
                return ((ushort)(this["InitialStraySearchTimeSec"]));
            }
            set {
                this["InitialStraySearchTimeSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public ushort StrayUpdateIntervalSec {
            get {
                return ((ushort)(this["StrayUpdateIntervalSec"]));
            }
            set {
                this["StrayUpdateIntervalSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Standard")]
        public global::Impinj.OctaneSdk.TransitionZoneRange TransitionZoneRange {
            get {
                return ((global::Impinj.OctaneSdk.TransitionZoneRange)(this["TransitionZoneRange"]));
            }
            set {
                this["TransitionZoneRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public ushort TOITagAgeSec {
            get {
                return ((ushort)(this["TOITagAgeSec"]));
            }
            set {
                this["TOITagAgeSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public ushort StrayTagAgeSec {
            get {
                return ((ushort)(this["StrayTagAgeSec"]));
            }
            set {
                this["StrayTagAgeSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public ushort TOISession {
            get {
                return ((ushort)(this["TOISession"]));
            }
            set {
                this["TOISession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public ushort StraySession {
            get {
                return ((ushort)(this["StraySession"]));
            }
            set {
                this["StraySession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TagFilterEpc {
            get {
                return ((string)(this["TagFilterEpc"]));
            }
            set {
                this["TagFilterEpc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string Zone1Sectors {
            get {
                return ((string)(this["Zone1Sectors"]));
            }
            set {
                this["Zone1Sectors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string Zone2Sectors {
            get {
                return ((string)(this["Zone2Sectors"]));
            }
            set {
                this["Zone2Sectors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public ushort MaxTagsPerZone {
            get {
                return ((ushort)(this["MaxTagsPerZone"]));
            }
            set {
                this["MaxTagsPerZone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlotStrays {
            get {
                return ((bool)(this["PlotStrays"]));
            }
            set {
                this["PlotStrays"] = value;
            }
        }
    }
}
