//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GridTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap1 {
            get {
                object obj = ResourceManager.GetObject("Bitmap1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap10 {
            get {
                object obj = ResourceManager.GetObject("Bitmap10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap11 {
            get {
                object obj = ResourceManager.GetObject("Bitmap11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap12 {
            get {
                object obj = ResourceManager.GetObject("Bitmap12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap13 {
            get {
                object obj = ResourceManager.GetObject("Bitmap13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap14 {
            get {
                object obj = ResourceManager.GetObject("Bitmap14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap15 {
            get {
                object obj = ResourceManager.GetObject("Bitmap15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap16 {
            get {
                object obj = ResourceManager.GetObject("Bitmap16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap17 {
            get {
                object obj = ResourceManager.GetObject("Bitmap17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap18 {
            get {
                object obj = ResourceManager.GetObject("Bitmap18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap19 {
            get {
                object obj = ResourceManager.GetObject("Bitmap19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap2 {
            get {
                object obj = ResourceManager.GetObject("Bitmap2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap20 {
            get {
                object obj = ResourceManager.GetObject("Bitmap20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap21 {
            get {
                object obj = ResourceManager.GetObject("Bitmap21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap22 {
            get {
                object obj = ResourceManager.GetObject("Bitmap22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap23 {
            get {
                object obj = ResourceManager.GetObject("Bitmap23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap24 {
            get {
                object obj = ResourceManager.GetObject("Bitmap24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap25 {
            get {
                object obj = ResourceManager.GetObject("Bitmap25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap26 {
            get {
                object obj = ResourceManager.GetObject("Bitmap26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap27 {
            get {
                object obj = ResourceManager.GetObject("Bitmap27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap28 {
            get {
                object obj = ResourceManager.GetObject("Bitmap28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap29 {
            get {
                object obj = ResourceManager.GetObject("Bitmap29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap3 {
            get {
                object obj = ResourceManager.GetObject("Bitmap3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap30 {
            get {
                object obj = ResourceManager.GetObject("Bitmap30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap31 {
            get {
                object obj = ResourceManager.GetObject("Bitmap31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap32 {
            get {
                object obj = ResourceManager.GetObject("Bitmap32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap33 {
            get {
                object obj = ResourceManager.GetObject("Bitmap33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap34 {
            get {
                object obj = ResourceManager.GetObject("Bitmap34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap35 {
            get {
                object obj = ResourceManager.GetObject("Bitmap35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap36 {
            get {
                object obj = ResourceManager.GetObject("Bitmap36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap37 {
            get {
                object obj = ResourceManager.GetObject("Bitmap37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap38 {
            get {
                object obj = ResourceManager.GetObject("Bitmap38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap39 {
            get {
                object obj = ResourceManager.GetObject("Bitmap39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap4 {
            get {
                object obj = ResourceManager.GetObject("Bitmap4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap40 {
            get {
                object obj = ResourceManager.GetObject("Bitmap40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap41 {
            get {
                object obj = ResourceManager.GetObject("Bitmap41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap42 {
            get {
                object obj = ResourceManager.GetObject("Bitmap42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap43 {
            get {
                object obj = ResourceManager.GetObject("Bitmap43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap44 {
            get {
                object obj = ResourceManager.GetObject("Bitmap44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap45 {
            get {
                object obj = ResourceManager.GetObject("Bitmap45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap46 {
            get {
                object obj = ResourceManager.GetObject("Bitmap46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap47 {
            get {
                object obj = ResourceManager.GetObject("Bitmap47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap48 {
            get {
                object obj = ResourceManager.GetObject("Bitmap48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap49 {
            get {
                object obj = ResourceManager.GetObject("Bitmap49", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap5 {
            get {
                object obj = ResourceManager.GetObject("Bitmap5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap50 {
            get {
                object obj = ResourceManager.GetObject("Bitmap50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap51 {
            get {
                object obj = ResourceManager.GetObject("Bitmap51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap52 {
            get {
                object obj = ResourceManager.GetObject("Bitmap52", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap6 {
            get {
                object obj = ResourceManager.GetObject("Bitmap6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap7 {
            get {
                object obj = ResourceManager.GetObject("Bitmap7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap8 {
            get {
                object obj = ResourceManager.GetObject("Bitmap8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bitmap9 {
            get {
                object obj = ResourceManager.GetObject("Bitmap9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
